# Generated by Django 5.1.6 on 2025-03-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parser',
            options={'ordering': ['name'], 'verbose_name': 'Парсер', 'verbose_name_plural': 'Парсеры'},
        ),
        migrations.AlterField(
            model_name='parser',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
