# Generated by Django 5.1.6 on 2025-03-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('monitoring_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
