# Generated by Django 5.1.6 on 2025-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('gearbox', models.CharField(blank=True, max_length=50, null=True)),
                ('owners', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('seller', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('drive', models.CharField(blank=True, max_length=50, null=True)),
                ('steering', models.CharField(blank=True, max_length=50, null=True)),
                ('ad_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Фильтр пользователя',
                'verbose_name_plural': 'Фильтры пользователей',
            },
        ),
    ]
