# Generated by Django 5.1.6 on 2025-03-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startcommandresponse',
            options={'verbose_name': 'Стартовое сообщение', 'verbose_name_plural': 'Стартовое сообщение'},
        ),
    ]
