# Generated by Django 5.1.6 on 2025-03-19 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0002_alter_startcommandresponse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Видео')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='startcommandresponse',
            options={'verbose_name': 'Приветственное сообщение', 'verbose_name_plural': 'Приветственное сообщение'},
        ),
    ]
