# Generated by Django 5.1.6 on 2025-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0003_broadcastmessage_alter_startcommandresponse_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Видео'),
        ),
    ]
