# Generated by Django 5.1.6 on 2025-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0004_alter_broadcastmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='video',
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Медиафайл'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, null=True, verbose_name='Тип медиафайла'),
        ),
    ]
