# Generated by Django 5.1.6 on 2025-06-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_update_created_at_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='drive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='engine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='gearbox',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='owners',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='seller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='steering',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
