FILTER_MAPPING = {
    "Площадка": "platform",
    "Цена": "price",
    "Марка": "brand",
    "Двигатель": "engine",
    "Пробег": "mileage",
    "Коробка": "gearbox",
    "Кол-во владельцев": "owners",
    "Состояние": "condition",
    "Продавец": "seller",
    "Город": "city",
    "Год выпуска": "year",
    "Тип кузова": "body_type",
    "Цвет кузова": "color",
    "Привод": "drive",
    "Руль": "steering",
    "Тип объявлений": "ad_type",
}
